## Reads version from version.txt and sets project version variables.

file(READ "${CMAKE_SOURCE_DIR}/version.txt" VERSION_CONTENTS)
string(STRIP "${VERSION_CONTENTS}" PROJECT_VERSION_STRING)
string(REPLACE "." ";" VERSION_LIST "${PROJECT_VERSION_STRING}")
list(GET VERSION_LIST 0 PROJECT_VERSION_MAJOR)
list(GET VERSION_LIST 1 PROJECT_VERSION_MINOR)
list(GET VERSION_LIST 2 PROJECT_VERSION_PATCH)

message(STATUS "CodeDupDetector version: ${PROJECT_VERSION_STRING}")
